### ISSUE TITLE
Ogar Experimental Mode, red viruses have no limit

### ISSUE THREAD

**Issue by NNickey** [forairan/Ogar#106]
Are the red viruses allowed to keep spewing out with no limit?

It can cause slight lag or sometimes prevent me from moving my character, making a bot kill me.

Edit: Will upload gif soon.

**Comment by vram4** [comment]
The food they spawn are limited by your max food amount.

**Comment by batbug** [comment]
@vram4 actually there is another bug with red viruses. If you feed them big enough (like 20000 mass) they become so big, so that they never get into the player's viewbox. So they basically become invisible. 

There are 2 solutions for that. 

1) Limit the red virus max size:

   	// Calculations
        var len = r - (check.getSize() / 2) >> 0; 
        if ((this.abs(this.position.x - check.position.x) < len) && (this.abs(this.position.y - check.position.y) < len)) {
            // Eats the cell
            gameServer.removeNode(check);
            this.mass += check.mass;
       +     this.mass = Math.min(this.mass,5555);

or the second solution - 

2) change the visiblenodes calculation for big viruses:

Cell.prototype.visibleCheck = function(box,centerPos) {
    // Checks if this cell is visible to the player
+	if (this.cellType == 2 && this.mass > 199) {
+		return true;
+	}
+	else {
		return this.collisionCheck(box.bottomY,box.topY,box.rightX,box.leftX);
+	}
};

**Comment by batbug** [comment]
now you get the idea.
but actually both solutions have negative sizes.

1) users love feeding red viruses to the hige sizes. But since the collision region is square (not  circle), at big virus sizes they get killed way too far from red virus. And they can't even reach the spawned food

2) another negative with 2nd solution - we send to the client coords of all red viruses. Could be used as a cheat if client has unlimited zoom

**Comment by batbug** [comment]
Maybe it's time to make the collision box round, not square?

**Comment by vram4** [comment]
A square collision box is just easier for node to process. There should be additional code that checks if the cell is in range but i got too lazy. As for the invisibility, i could use the same algorithm that i do with detecting if large cells are in the viewbox.
