### ISSUE TITLE
Split blobs do not move and only the main blob can continue to move.

### ISSUE THREAD

**Issue by electronoob** [forairan/Ogar#18]
Herpderp

So during game play you roll around, split yourself into a billion cells and it's all fun and games until you get into a battle.

Imagine this - there we are in heat of battle - I'm in 3 large blobs and avoiding 1 larger blob who I am escaping from when suddenly... 2 of my blobs forget how to run away and they just stay frozen in place while the main blob doesn't even bother looking back to see how they are doing.

At this very moment, it seems that my opponent is unable to split kill me either as the command has no effect. This was expressed to me over mumble by the player.

30 seconds later, one of our buddies who was playing on our other instance of Ogar pipes up on mumble expressing surprise at just experiencing the very same bug.

We look forward to another awesome bug squish.

**Comment by electronoob** [comment]
In addition to this report, as it is related:

If someone ate half of you at the same time as you split, you may be left with just one uncontrollable blob.

**Comment by vram4** [comment]
Sorry for the delay, i was sleeping. Im going to look into it immediately.

**Comment by vram4** [comment]
Wwhen this bug happened, were you near the border?

**Comment by vram4** [comment]
I am unable to reproduce the bug with getting stuck when splitting, even when i had debug code that would instantly kill new cells from splitting. However, i do have an idea on why this might be happening. I'll be pushing a "fix" soon.

There is however a bug with cells getting stuck if they move past the border, usually it happens with extremely large cells. If those large cells split near the border, because of the collision code, they would get pushed around. The pushing would cause them to move past the border (and get stuck in place).

**Comment by electronoob** [comment]
When I saw it happen it was a fair distance away from the right border, I couldn't have split or eject mass that far to the border though so I think that means it was most likely not the border causing it - but I'm pulling that incredible debugging information right out from my behind.

**Comment by vram4** [comment]
I've identified the issue and was able to recreate it. I already wrote a fix, but i'll release it once it passes my stress test on the server.

**Comment by electronoob** [comment]
yep,. awesome thank you and I will then roll that out to our users.

**Comment by vram4** [comment]
I pushed a potential fix which includes warnings in the console if anything weird occurs. Please let me know if it happens again.
