### ISSUE TITLE
cells skins

### ISSUE THREAD

**Issue by bisguzar** [forairan/Ogar#38]
can we add skin for cells ? etc: ayy lmao, Turkey, Reddit

**Comment by electronoob** [comment]
thats client side

**Comment by bisguzar** [comment]
how to ?

**Comment by underc0de** [comment]
@bisguzar It's client side as electronoob said.

That means that the skins are not related with the server so asking that here doesn't make sense. I think the reason you can't see skins is because you don't have the skins folder. 

Create the folder "skins" and add the png files. (Ex: http://agar.io/skins/reddit.png)
