### ISSUE TITLE
What is this Magic number?

### ISSUE THREAD

**Issue by Luchanso** [forairan/Ogar#43]
https://github.com/forairan/Ogar/blob/master/src/entity/Cell.js#L171

```JS
var move = collisionDist - dist + 5;
```

Why you use this 5?

**Comment by maixuanhan** [comment]
Code is changed. Please edit your question or should we close this topic?

**Comment by Ephemerality** [comment]
It's now on PlayerCell.js line 89. The 5 is the amount that a cell is pushed when your own cells are colliding. I suppose a config/const value could be put in somewhere for it, I'll leave that up to vram, but you start seeing some weird behaviour if it's much higher than 5 (for a lot of fun, try 100)!

**Comment by Jackster35** [comment]
A lot people on our forums hate the "pushing" feature of the game. People use it as an advantage on the teams mode allowing them to cheat for the other team.

**Comment by Ephemerality** [comment]
After playing around a little, I think part of the '5' being there was because without it, your cells squish together a little bit.  
I checked out the Teams.js and I don't think the pushing in teams mode is really intended to work the way it does. The stuff starting at line 114 is there to prevent the cells from overlapping. I tried pushing a smaller cell with a single much larger one and it moved a tiny bit, only a few pixels after pushing for a while. However, when I split into many cells and moved around the other one a bunch, it moved unpredictably. So I think there's something weird going on there that needs to get looked into further.

**Comment by vram4** [comment]
@Ephemerality Were you using the client i gave you? That one doesnt have the movement smoothing that the default client has, hence the jiggly movement.

**Comment by Ephemerality** [comment]
Nope, vanilla.

**Comment by maixuanhan** [comment]
@Jackster35 : my colleagues hate that also (that was the reason I make _TeamX_ mode). They also hate moving virus, they like splitting virus (so, I'll tweak TeamX mode so that moving virus can be configurable (by code, not ini file) in that mode). Thanks God! they love 'eating teammates' of that mode. :joy_cat:

Comeback about team cell collision, I think vanilla has changed lately. Weeks ago, I played on vanilla and also crazy about 'pushing thing'. Yesterday, it changed. The new cell will move to its target position. If that position is inside a team cell, it will be pushed to outside of that cell. Direction of second moving is vector AB where A is the center of bigger cell, B is the center of smaller cell. (If A is same to B, any direction makes sense). After the second moving, if it collides with other cell, then it starts pushing. Same situation if the new cell overlaps a smaller cell, but now, the small cell will be moved. In other word, smaller cell of a overlap case will be moved outside the bigger one.

**Comment by Agarian** [comment]
it is nowhere now.
